import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      'poppins-bold': ['poppins-bold', 'Arial', 'sans-serif'],
      'poppins-extra-bold': ['poppins-extra-bold', 'Arial', 'sans-serif'],
      'poppins-light': ['poppins-light', 'Arial', 'sans-serif'],
      'poppins-medium': ['poppins-medium', 'Arial', 'sans-serif'],
      'poppins-regular': ['poppins-regular', 'Arial', 'sans-serif'],
      'poppins-thin': ['poppins-thin', 'Arial', 'sans-serif']
    },
    fontSize: {
      "f-8": "8px",
      "f-10": "10px",
      "f-11": "11px",
      "f-12": "12px",
      "f-13": "13px",
      "f-14": "14px",
      "f-15": "15px",
      "f-16": "16px",
      "f-17": "17px",
      "f-18": "18px",
      "f-19": "19px",
      "f-20": "20px",
      "f-24": "24px",
      "f-28": "28px",
      "f-32": "32px",
      "f-40": "40px",
      "f-56": "56px",
      "f-72": "72px"
    },
    screens: {
      xs: '375px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1366px'
    },
    colors: {
      primary: {
        darkBlue: '#001A41',
        rzaRed: '#FF0025',
        rzaBlack: '#000000',
        rzaWhite: '#ffffff',
        rzaGrey10: '#FAFAFB',
        rzaGrey20: '#EDECF0',
        rzaGrey40: '#CCCFD3',
        rzaGrey50: '#79838D',
        rzaGrey60: '#99A0A7',
        rzaGrey80: '#66707A',
        rzaGrey90: '#5F6368',
        rzaGrey100: '#4E5764',
      },
      secondary: {
        rzaRed: '#ED0226',
        rzaDarkRed: '#B90024',
        rzaErrorRed: '#BC1D42',
        rzaLightDarkRed: '#F2E2E2',
        rzaLightRed: '#FCF4F4',
        rzaSemanticRead: '#FEEFEB',
        rzaMustard: '#FDA22B',
        rzaLightMustard: '#FFEED8',
        rzaBlue: '#0050AE',
        rzaOtherLightBlue: '#1A73E8',
        rzaLightBlue: '#EDF5FC',
        rzaSoftBlue: '#CDD6E7',
        rzaOtherSoftBlue: "#E9F6FF",
        rzaDarkBlue100: '#F9F9FA',
        rzaGreen: '#008E53',
        rzaCard: '#F6F3F3',
        rzaDivider: '#C4C4C4',
        rzaGoldenYellow100: '#F6AB2F',
        rzaShadesBlue: '#344960',
        rzaShades300: '#DFE2E7',
        rzaShades600: '#334867',
        rzaPink: '#FCF4F4',
        rzaShadeInkBlade: '#001122',
        rzaShadeGray50: '#79838D',
        rzaTagBackgound: '#E9E4E4',
        rzaSunsetOrange: '#FE6E00',
        rzaSecondaryGreyBg: '#F5F6FA',
        rzaSpearminGreen: '#EEF9F4',
        rzaForestGreen100: '#1D9940',
        rzaWarningOrange: '#D44000',
        rzaSemanticBlue: '#E9F6FF',
        rzaCultured: '#F7F7F7',
        rzaCoolGrey: '#8C99AC',
        rzaLightGrey: '#CCD1D9',
        rzaAliceBlue: '#E9F6FF',
        rzaVenetianRed: '#BC1D42',
        rzaCadetBlue: '#B3BAC6',
        rzaPapayaWhip: '#FEF3D4',
        rzaTopaz: '#FED27F',
        rzaWarningYellow: '#D9801F',
        rzaTealDeer: '#9AEEAB',
        rzaHoneyDew: '#EDFCF0',
        rzaCornFlower: '#CF2E01',
        rzaBrightGray: '#EBEEEF',
        rzaShadowGray: '#7A7A7A',
        disabled: '#f1f1f4',
        disabled02: '#E9E8ED',
        coolGray600: '#757F90',
        deepSkyBlue: '#0f78cb'
      },
      shade: {
        grey: {
          "100": "#353941"
        }
      }
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
} satisfies Config;
