name: Next.js to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      chrome: # Adds the Google Chrome service
        image: google-chrome:latest
        credentials: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Copy built app from previous job
        uses: actions-minimal-copy-file@v1
        with:
          from_job: build
          from_path: .  # Copy from the build job's directory
          target_path: .  # Target directory in the test job

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Run test before deploy
    environment: production  # Use if you have environment protection in Vercel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
