name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Menggunakan versi Node.js 18.x yang kompatibel dengan Next.js

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      - name: Build Next.js project
        run: npm run build  # Pastikan perintah build sesuai dengan konfigurasi Next.js Anda

      # Jalankan aplikasi Next.js di background dengan perintah dev (development mode)
      - name: Start Next.js application in development mode
        run: |
          npm run dev &  # Menjalankan aplikasi di background dalam mode dev (development)

      # Tunggu hingga aplikasi siap dengan menggunakan curl
      - name: Wait for app to start
        run: |
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for application to start..."
            sleep 5  # Tunggu hingga aplikasi benar-benar siap
          done
          echo "Application is up!"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build  # Menunjukkan bahwa job e2e-tests hanya akan dijalankan setelah job build selesai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      # Jalankan Cypress untuk melakukan E2E testing
      - name: Run Cypress tests
        run: |
          npx cypress run --headless --browser chrome  # Menjalankan Cypress dalam mode headless dengan browser Chrome

  deploy:
    runs-on: ubuntu-latest
    needs: e2e-tests  # Menunjukkan bahwa job deploy hanya akan dijalankan setelah job e2e-tests selesai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Gunakan Node.js versi 18.x

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}  # Menambahkan --prod untuk deploy ke production dan --yes untuk konfirmasi otomatis
