name: Next.js with Cypress and Vercel Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CYPRESS_BASE_URL: ${{ secrets.NEXT_BASE_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

  cypress-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with official action
        uses: cypress-io/github-action@v6
        with:
          build: npm run build  # Perintah build
          start: npm start      # Perintah start untuk test
          reuse-cypress-cache: true
        env:
          CYPRESS_BASE_URL: ${{ secrets.NEXT_BASE_URL }}
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: cypress-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
