name: Next.js with Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CYPRESS_SLOW_MO: 0
  CYPRESS_BASE_URL: ${{ secrets.NEXT_BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # Debug: Show build information
      - name: Show build logs
        run: |
          echo "Build directory contents:"
          ls -la .next
          echo "Number of files in .next:"
          find .next | wc -l

      # Try uploading all files in the directory
      - name: Upload .next directory with glob pattern
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: ./.next/**

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      chrome:
        image: docker://brightsec/chrome-cypress:latest
        options: --headless

    steps:
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      # Download and handle all artifacts
      - name: Download .next artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .

      # Debug: Check if the artifact was downloaded correctly
      - name: Check artifact contents
        run: |
          ls -la
          ls -la .next || echo ".next directory not found"

      # Reinstall dependencies (test environment may be different)
      - name: Reinstall dependencies
        run: npm ci

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --headless
        env:
          CI: true
          BASE_URL: ${{ secrets.NEXT_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
