name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Menggunakan versi Node.js 18.x yang kompatibel dengan Next.js

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      - name: Build Next.js project
        run: npm run build  # Pastikan perintah build sesuai dengan konfigurasi Next.js Anda

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Menunjukkan bahwa job deploy hanya akan dijalankan setelah job build selesai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Gunakan Node.js versi 18.x

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}  # Menambahkan --prod untuk deploy ke production dan --yes untuk konfirmasi otomatis
