name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Menggunakan versi Node.js 18.x yang kompatibel dengan Next.js

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      - name: Build Next.js project
        run: npm run build  # Pastikan perintah build sesuai dengan konfigurasi Next.js Anda

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      chrome: # Adds the Google Chrome service
        image: google-chrome:latest
        credentials: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Copy built app from previous job
        uses: actions-minimal-copy-file@v1
        with:
          from_job: build
          from_path: .  # Copy from the build job's directory
          target_path: .  # Target directory in the test job

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless
        
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Menunjukkan bahwa job deploy hanya akan dijalankan setelah job build selesai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Gunakan Node.js versi 18.x

      - name: Install dependencies
        run: npm install  # Jika Anda menggunakan yarn, ganti dengan `yarn install`

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}  # Menambahkan --prod untuk deploy ke production dan --yes untuk konfirmasi otomatis
